### ISSUE TITLE
Move archetypes to separate files

### ISSUE THREAD

**Issue by rooneg** [5srd/5srd.github.io#5]
We should consider moving the various class archetypes out to separate files, with a table of them in the class's main page (like on the monsters page). This would let people who are building a custom SRD for their own system easily drop in their own archetypes.

**Comment by drumanagh** [comment]
That's a pretty good idea.

I've also been experimenting some with mechanizing the classes more, automatically generating a class table from a data format with a list of abilities. It's pretty straightforward for martials, but I haven't figured a good way to track spell slots yet.

**Comment by rooneg** [comment]
Thanks! That looks awesome.
